/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.inazumastation.app;

public final class R {
  public static final class color {
    public static final int bg_card=0x7f010000;
    public static final int bg_card_light=0x7f010001;
    public static final int bg_dark=0x7f010002;
    public static final int bg_darker=0x7f010003;
    public static final int cyan_accent=0x7f010004;
    public static final int gold_glow=0x7f010005;
    public static final int gold_primary=0x7f010006;
    public static final int pitch_green=0x7f010007;
    public static final int pitch_line=0x7f010008;
    public static final int text_muted=0x7f010009;
    public static final int text_white=0x7f01000a;
  }
  public static final class drawable {
    public static final int bg_badge_generic=0x7f020000;
    public static final int bg_bottom_bar=0x7f020001;
    public static final int bg_btn_gold=0x7f020002;
    public static final int bg_card=0x7f020003;
    public static final int bg_card_gold=0x7f020004;
    public static final int bg_pitch=0x7f020005;
    public static final int bg_search=0x7f020006;
    public static final int bg_slot_empty=0x7f020007;
    public static final int bg_slot_player=0x7f020008;
  }
  public static final class id {
    public static final int bench_container=0x7f030000;
    public static final int bottom_nav_bar=0x7f030001;
    public static final int btn_back=0x7f030002;
    public static final int btn_dialog_clear_slot=0x7f030003;
    public static final int btn_filter_all=0x7f030004;
    public static final int btn_filter_earth=0x7f030005;
    public static final int btn_filter_fire=0x7f030006;
    public static final int btn_filter_wind=0x7f030007;
    public static final int btn_filter_wood=0x7f030008;
    public static final int btn_form_343=0x7f030009;
    public static final int btn_form_352=0x7f03000a;
    public static final int btn_form_4231=0x7f03000b;
    public static final int btn_form_433=0x7f03000c;
    public static final int btn_form_442=0x7f03000d;
    public static final int btn_reset_tactics=0x7f03000e;
    public static final int btn_save_tactics=0x7f03000f;
    public static final int btn_toggle_lang=0x7f030010;
    public static final int et_dialog_search=0x7f030011;
    public static final int et_search=0x7f030012;
    public static final int et_search_moves=0x7f030013;
    public static final int iv_detail_thumb=0x7f030014;
    public static final int iv_player_thumb=0x7f030015;
    public static final int layout_pitch=0x7f030016;
    public static final int list_dialog_players=0x7f030017;
    public static final int list_moves=0x7f030018;
    public static final int list_players=0x7f030019;
    public static final int nav_btn_moves=0x7f03001a;
    public static final int nav_btn_players=0x7f03001b;
    public static final int nav_btn_settings=0x7f03001c;
    public static final int nav_btn_tactics=0x7f03001d;
    public static final int nav_tv_moves=0x7f03001e;
    public static final int nav_tv_players=0x7f03001f;
    public static final int nav_tv_settings=0x7f030020;
    public static final int nav_tv_tactics=0x7f030021;
    public static final int slots_container=0x7f030022;
    public static final int tab_content_container=0x7f030023;
    public static final int tab_view_moves=0x7f030024;
    public static final int tab_view_players=0x7f030025;
    public static final int tab_view_settings=0x7f030026;
    public static final int tab_view_tactics=0x7f030027;
    public static final int tv_detail_desc=0x7f030028;
    public static final int tv_detail_elem=0x7f030029;
    public static final int tv_detail_extra=0x7f03002a;
    public static final int tv_detail_kana=0x7f03002b;
    public static final int tv_detail_name=0x7f03002c;
    public static final int tv_detail_pos=0x7f03002d;
    public static final int tv_detail_stats=0x7f03002e;
    public static final int tv_detail_title=0x7f03002f;
    public static final int tv_dialog_title=0x7f030030;
    public static final int tv_player_count=0x7f030031;
    public static final int tv_player_desc_preview=0x7f030032;
    public static final int tv_player_element=0x7f030033;
    public static final int tv_player_name=0x7f030034;
    public static final int tv_player_pos=0x7f030035;
    public static final int tv_player_series=0x7f030036;
  }
  public static final class layout {
    public static final int activity_main=0x7f040000;
    public static final int activity_player_detail=0x7f040001;
    public static final int dialog_select_player=0x7f040002;
    public static final int item_player=0x7f040003;
  }
  public static final class mipmap {
    public static final int ic_launcher=0x7f050000;
  }
  public static final class string {
    public static final int app_name=0x7f060000;
    public static final int search_hint=0x7f060001;
    public static final int search_moves_hint=0x7f060002;
    public static final int tab_moves=0x7f060003;
    public static final int tab_players=0x7f060004;
    public static final int tab_settings=0x7f060005;
    public static final int tab_tactics=0x7f060006;
  }
  public static final class style {
    public static final int AppTheme=0x7f070000;
  }
}