// 시리즈명을 원작의 온전하고 친숙한 한글 공식 이름으로 매핑해 주는 테이블입니다.
export const seriesTranslation = {
  'イナズマイレブン': '이나즈마 일레븐 (오리지널)',
  'イナズマイレブン2 脅威の侵략者 ファイア／ブリザード': '이나즈마 일레븐 2: 위협의 침략자',
  'イナズマイレブン2 脅威の侵略者 ファイア／ブリザード': '이나즈마 일레븐 2: 위협의 침략자',
  'イナズマイレブン3 世界への挑戦!! スパーク／ボンバー／ジ・オーガ': '이나즈마 일레븐 3: 세계로의 도전!!',
  'イナズマイレブンGO シャイン／ダーク': '이나즈마 일레븐 GO',
  'イナズマイレブンGO2 クロノ・ストーン ネップ우／ライメイ': '이나즈마 일레븐 GO 2: 크로노 스톤',
  'イナズマイレブンGO2 クロノ・ストーン ネップウ／ライメイ': '이나즈마 일레븐 GO 2: 크로노 스톤',
  'イナズマイレブンGO ギャラクシー ビッグバン／スーパーノヴァ': '이나즈마 일레븐 GO: 갤럭시',
  'イナズマイレブン アレスの天秤': '이나즈마 일레븐: 아레스의 천칭',
  'イナズマイレブン オリオンの刻印': '이나즈마 일레븐: 오리온의 각인',
  'イナズマイレブン 英雄たちのヴィクトリーロード': '이나즈마 일레븐: 영웅들의 빅토리 로드',
  '-': ''
};

// 이름이 겹치는 중복 캐릭터들을 구분하기 위해 이름 뒤에 붙여줄 버전을 정의한 한글 매핑 테이블입니다.
export const seriesVersionTranslation = {
  'イナズマイレブン': '오리지널',
  'イナズマイレブン2 脅威の侵略者 ファイア／ブリザード': '2편',
  'イナズマイレブン3 世界への挑戦!! スパーク／ボンバー／ジ・オーガ': '3편',
  'イナズマイレブンGO シャイン／ダーク': 'GO',
  'イナズマイレブンGO2 クロノ・ストーン ネップウ／ライメイ': '크로노 스톤',
  'イナズマイレブンGO ギャラクシー ビッグバン／スーパーノヴァ': '갤럭시',
  'イナズマイレブン アレスの天秤': '아레스의 천칭',
  'イナズマイレブン オリオンの刻印': '오리온의 각인',
  'イナズマイレブン 英雄たちのヴィクトリーロード': '빅토리 로드',
  '-': ''
};

// 선수 도감 카드 및 상세 페이지에서 사용하는 인물 카테고리(분류)를 한글로 변환해 주는 맵입니다.
export const categoryTranslation = {
  '選手': '선수',
  'マネージャー': '매니저',
  '監督': '감독',
  'コーチ': '코치',
  '選手\n監督': '선수 겸 감독',
  '-': '미정'
};

// 데이터베이스(characters.json) 내의 총 193가지 모든 고유 소속 팀명을 한글 공식 명칭으로 완벽하게 매핑한 사전입니다.
// 이 테이블에 일어 명칭이 등록되어 있으면 번역 API를 호출하지 않고 화면에 즉시 깨끗한 한글 이름이 표출됩니다.
export const teamTranslation = {
  "-": "-",
  "からくり兵馬俑": "기계 병마용",
  "アイドル同好会": "아이돌 동호회",
  "アクア・ハーミット": "아쿠아 허밋",
  "アラブの火の鳥軍団": "아랍의 불새 군단",
  "アンリミテッドシャイニング": "언리미티드 샤이닝",
  "アースイレブン": "어스 일레븐",
  "イクサルフリート": "익살 플리트",
  "イナズ마ジャパン": "이나즈마 재팬",
  "イナズマジャパン": "이나즈마 재팬",
  "イナズマレジェンドジャパン": "이나즈마 레전드 재팬",
  "イプシロン": "입실론",
  "ウルフズ＆ドックス": "울프즈 & 독스",
  "エターナルダンサーズ": "이터널 댄서즈",
  "エルドラドチーム０１": "엘도라도 팀 01",
  "エルドラドチーム０２": "엘도라도 팀 02",
  "エルドラドチーム０３": "엘도라도 팀 03",
  "エンシャントダーク": "에인션트 다크",
  "オカルト研究会": "오컬트 연구회",
  "オルフェウス": "오르페우스",
  "カオス": "카오스",
  "ガル": "갈",
  "ガードンイレブン": "가돈 일레븐",
  "ギル": "길",
  "クィーンズ": "퀸즈",
  "クイズ研究会": "퀴즈 연구회",
  "クリム・ハウンド": "크림 하운드",
  "クロノストーム": "크로노 스톰",
  "ゲートキーパーズ": "게이트 키퍼즈",
  "ゴルド・ベア": "골드 베어",
  "サウザンクロウ": "서전 크로우",
  "サザナーライレブン": "사자나라 일레븐",
  "サブキャラクター": "서브 캐릭터",
  "サンドリアスイレブン": "샌드리아 일레븐",
  "サーフィン部": "서핑부",
  "ザナーク・ストレンジャーズ": "자나크 스트레인저스",
  "ザナーク・ドメイン": "자나크 도메인",
  "ザン": "잔",
  "ザ・キングダム": "더 킹덤",
  "ザ・グレイトホーン": "더 그레이트 혼",
  "ザ・ジェネシス": "더 제네시스",
  "ザ・ラグーン": "더 라군",
  "シャイニングサタンズ": "샤이닝 사탄즈",
  "シャムシール": "샤무시르",
  "ジェミニストーム": "제미니 스톰",
  "ジ・エグゼラー": "디 엑셀러",
  "ジ・エンパイア": "디 엠파이어",
  "スターユニコーン": "스타 유니콘",
  "ストームウルフ": "스톰 울프",
  "スノウ・ウィーゼル": "스노우 위젤",
  "スペースランカーズ": "스페이스 랭커즈",
  "スーパーノヴァ": "슈퍼노바",
  "ゼロ": "제로",
  "ダイヤモンドダスト": "다이아몬드 더스트",
  "ダンス部": "댄스부",
  "ダークエンジェル": "다크 엔젤",
  "ダークエンペラーズ": "다크 엠페러즈",
  "チョウキンウンズ": "쵸킨운즈",
  "チーム・ガルシルド": "팀 갈실드",
  "チームＫ": "팀 K",
  "ツキガミの一族": "츠키가미 일족",
  "テニス部": "테ニス부",
  "テンマーズ": "텐마즈",
  "デザートライオン": "디저트 라이언",
  "デストラクチャーズ": "디스트럭처스",
  "デモンズホーン": "데몬즈 혼",
  "ドラゴンリンク": "드래곤 링크",
  "ナイツオブクィーン": "나이츠 오브 퀸",
  "ナイト・ヴァイパー": "나이트 바이퍼",
  "ネオジャパン": "네오 재팬",
  "ノーザンファング": "노던 팽",
  "ハンドボール部": "핸드볼부",
  "バスケットボール部": "농구부",
  "バドミントン部": "배드민턴부",
  "バルセロナ・オーブ": "바르셀로나 오브",
  "バレーボール部": "배구부",
  "パーフェクト・カスケイド": "퍼펙트 카스케이드",
  "ビッグウェイブス": "빅 웨이브스",
  "ビッグバン": "빅뱅",
  "ファイアードラゴン": "파이어 드래곤",
  "ファラム・ディーテ": "파람 디테",
  "ブロッケンボーグ": "브로켄보그",
  "プロトコル・オメガ": "프로토콜 오메가",
  "プロトコル・オメガ２．０": "프로토콜 오메가 2.0",
  "プロトコル・オメガ３．０": "프로토콜 오메가 3.0",
  "プロミネンス": "프로미넌스",
  "ボディビルダー部": "보디빌더부",
  "マジック研究会": "마술 연구회",
  "マッハタイガー": "마하 타이거",
  "メタル研究会": "메탈 연구회",
  "ヤングイナズマ": "영 이나즈마",
  "ユニコーン": "유니콘",
  "ラグビー部": "럭비부",
  "ラトニークイレブン": "라토니크 일레븐",
  "リトルギガント": "리틀 기간트",
  "レジスタンスジャパン": "레지스탕스 재팬",
  "レッドバイソン": "레드 바이슨",
  "レッドマタドール": "레드 마타도르",
  "ローズグリフォン": "로즈 그리폰",
  "ヴァンプティム": "뱀프 팀",
  "一番街サリーズ": "1번가 샐리즈",
  "万能坂中": "반노자카 중학교",
  "世宇子中": "제우스 중학교",
  "二戸川中": "니토가와 중학교",
  "京前嵐山中": "쿄마에아라시야마 중학교",
  "伊那国中": "이나쿠니 중학교",
  "伐天・陽花戸中": "바츠텐 요카토 중학교",
  "偉仁銘文堂": "이인명문당",
  "傘美野中": "카사미노 중학교",
  "利根川東泉中": "토네가와토센 중학교",
  "剣道部": "검도부",
  "北陽学園": "호쿠요 학원",
  "千羽山中": "센바야마 중학교",
  "卓球부": "탁구부",
  "卓球部": "탁구부",
  "南雲原ショップキーパーズ": "나구모하라 숍키퍼즈",
  "南雲原中": "나구모하라 중학교",
  "合唱部": "합창부",
  "吹奏楽部": "취주악부",
  "囲碁・将棋部": "바둑 장기부",
  "大海原中": "오오미하라 중학교",
  "大阪ギャルズ・ＣＣＣ": "오사카 갤스 CCC",
  "天河原中": "텐가와라 중학교",
  "天照・世宇子中": "아마테라스 제우스 중학교",
  "天空の使徒": "천공의 사도",
  "宇宙研究会": "우주 연구회",
  "尾刈斗中": "오컬트 중학교",
  "帝国学園": "제국학원",
  "幻影学園": "겐에이 학원",
  "御影専農中": "미카게센노 중학교",
  "応援団": "응원단",
  "戦国伊賀島中": "센고쿠이가지마 중학교",
  "新聞部": "신문부",
  "新雲学園": "아라쿠모 학원",
  "日本代表候補Ｂ": "일본 대표 후보 B",
  "日本舞踊部": "일본 무용부",
  "星章学園": "세이쇼 학원",
  "月山国光中": "갓산쿠니미츠 중학교",
  "木戸川清修中": "키도카와세이슈 중학교",
  "東風異国館": "코치이코쿠칸",
  "柔道部": "유도부",
  "栄都学園": "에이토 학원",
  "格闘技部": "격투기부",
  "樹海チーム": "쥬카이 팀",
  "水泳부": "수영부",
  "水泳部": "수영부",
  "水球部": "수구부",
  "永世学園": "에이세이 학원",
  "法令館中": "호레이칸 중학교",
  "海カモメサッカークラブ": "우미카모메 축구 클럽",
  "海洋生物部": "해양생물부",
  "海王学園": "카이오 학원",
  "演劇部": "연극부",
  "漫画研究会": "만화 연구회",
  "漫遊寺中": "만유지 중학교",
  "無所属": "무소속",
  "無敵のジャイアント": "무적의 자이언트",
  "王帝月ノ宮中": "오우테이츠키노미야 중학교",
  "王牙学園": "왕가 학원",
  "生徒会": "학생회",
  "白恋中": "하쿠렌 중학교",
  "白鹿組": "시로시카 조직",
  "百人一首クラブ": "백인일수 동아리",
  "相撲部": "씨름부",
  "真・帝国学園": "신 제국학원",
  "秋空チャレンジャーズ": "아키조라 챌린저스",
  "秋葉名戸学園": "아키하노토 학원",
  "稲妻ＫＦＣ": "이나즈마 KFC",
  "緑ヶ丘中": "미도리가오카 중학교",
  "美化委員": "미화위원회",
  "美濃道三中": "미노도산 중학교",
  "美術部": "미술부",
  "聖堂山中": "세이도우잔 중학교",
  "英愛学園": "에이아이 학원",
  "茶道部": "다도부",
  "西ノ宮中": "西노미야 중학교",
  "西ノ宮中": "니시노미야 중학교",
  "足球雑技団": "축구 잡기단",
  "路地裏バックキックス": "뒷골목 백킥스",
  "軽音楽部": "경음악부",
  "野球部チーム": "야구부 팀",
  "野生中": "노세 중학교",
  "銘蘭学院": "메이란 학원",
  "陸上部": "육상부",
  "陽花戸中": "요카토 중학교",
  "雷門セカンドチーム": "라이몬 2군",
  "雷門ファーストチーム": "라이몬 1군",
  "雷門中": "라이몬 중학교",
  "雷門ＯＢ": "라이몬 OB",
  "電子計算機部": "컴퓨터부",
  "青葉学園": "아오바 학원",
  "革命選抜チーム": "레볼루션 선발",
  "風紀委員": "선도부",
  "魔界軍団Ｚ": "마계군단 Z",
  "黒の騎士団": "검은 기사단",
  "ＳＰフィクサーズ": "SP 픽서즈",
  "e스포츠부": "e스포츠부",
  "ｅスポーツ部": "e스포츠부",
  "雷門中\nイナズマジャパン": "라이몬 중학교\n이나즈마 재팬"
};

/**
 * 선수의 한글 이름이 데이터베이스 내 다른 선수들과 중복되는지 체크하여,
 * 중복이 있을 때만 이름 뒤에 시리즈 버전 정보(예: "(오리지널)", "(아레스의 천칭)" 등)를 붙여 반환합니다.
 * 중복되지 않는 독자 캐릭터인 경우에는 본명 그대로를 보여주어 화면을 깔끔하게 유지합니다.
 * 
 * @param {Object} player - 대상 선수 객체
 * @param {Array} allPlayers - 전체 선수 데이터베이스 배열
 * @returns {string} 최종 UI에 표출할 가공된 선수 이름
 */
export function getPlayerDisplayName(player, allPlayers) {
  if (!player) return '';
  if (!player.name) return '';

  // 전체 데이터베이스에서 동일한 이름을 가진 선수들이 몇 명 존재하는지 필터링합니다.
  const sameNamePlayers = allPlayers.filter(p => p.name === player.name);

  // 이름이 같은 캐릭터가 2명 이상 있는 경우 버전을 덧붙여서 구분해 줍니다.
  if (sameNamePlayers.length > 1 && player.series) {
    // 일어 시리즈 명칭을 한글화 매핑에서 확인하여 짧은 버전명으로 변환합니다.
    const version = seriesVersionTranslation[player.series] || player.series;
    return version ? `${player.name} (${version})` : player.name;
  }

  // 중복이 없다면 기존 이름을 온전히 리턴합니다.
  return player.name;
}

/**
 * 기계 번역된 텍스트를 축구 상황과 인게임 캐릭터 소개에 맞게 매끄러운 한글로 다듬어 주는 필터 함수입니다.
 * 어색하게 직역된 어휘나 문말 종결 방식을 한국어 정서와 이나즈마 일레븐 공식 로컬라이징 명칭에 맞춰 교정합니다.
 * 
 * @param {string} text - 원본 번역 텍스트
 * @returns {string} 교정이 완료된 번역 텍스트
 */
export function refineTranslation(text) {
  if (!text) return '';

  let refined = text;

  // 번역 정제 치환 규칙 매핑 사전 (정규식 기반 순차 적용)
  const rules = [
    // 1. 축구 및 인게임 역할 용어 보정 (방어 -> 수비, 공격 -> 공격)
    { pattern: /디펜스/gi, replace: '수비' },
    { pattern: /오펜스/gi, replace: '공격' },
    { pattern: /디펜더/gi, replace: '수비수' },
    { pattern: /포워드/gi, replace: '공격수' },
    { pattern: /미드필더/gi, replace: '미드필더' },
    { pattern: /골키퍼/gi, replace: '골키퍼' },
    { pattern: /키퍼/gi, replace: '골키퍼' },
    { pattern: /방어는/g, replace: '수비는' },
    { pattern: /방어의/g, replace: '수비의' },
    { pattern: /방어력을/g, replace: '수비력을' },
    { pattern: /방어력/g, replace: '수비력' },
    { pattern: /방어/g, replace: '수비' },

    // 2. 어색한 직역체 조사 및 문장 결합 보정
    { pattern: /에의/g, replace: '에 대한' }, // への -> ~에의 -> ~에 대한
    { pattern: /으로의/g, replace: '으로 향하는' },

    // 3. 기계 번역 특유의 어조 윤문 및 행동 묘사 자연어화
    { pattern: /지지 않습니다/g, replace: '뒤지지 않는다' },
    { pattern: /지지 않는다/g, replace: '뒤지지 않는다' },
    { pattern: /뒤지지 않습니다/g, replace: '뒤지지 않는다' },
    { pattern: /마음을 가진다/g, replace: '마음을 지녔다' },
    { pattern: /마음을 가진/g, replace: '마음을 지닌' },
    { pattern: /을 가진/g, replace: '을 지닌' },
    { pattern: /를 가진/g, replace: '를 지닌' },
    { pattern: /을 가진다/g, replace: '을 지녔다' },
    { pattern: /를 가진다/g, replace: '를 지녔다' },
    { pattern: /포기하지 않는 강한 마음/g, replace: '포기하지 않는 강한 의지' },
    { pattern: /어떤 때라도/g, replace: '어떤 상황에서도' },

    // 4. 큰 몸, 巨体(거체) 등의 표현 한글 정제
    { pattern: /큰 몸을 사용한/g, replace: '커다란 체구를 살린' },
    { pattern: /큰 몸을 이용한/g, replace: '커다란 체구를 살린' },
    { pattern: /큰 몸을 살린/g, replace: '커다란 체구를 살린' },
    { pattern: /거대한 몸을 사용한/g, replace: '커다란 체구를 살린' },
    { pattern: /거대한 몸을 살린/g, replace: '커다란 체구를 살린' },
    { pattern: /거대한 몸을/g, replace: '커다란 체구를' },
    { pattern: /큰 몸을/g, replace: '커다란 체구를' },
    { pattern: /작은 체형/g, replace: '왜소한 체구' },
    { pattern: /작은 체구/g, replace: '왜소한 체구' },
    { pattern: /머리형/g, replace: '헤어스타일' },

    // 5. まさに(마사니) 및 수비 관련 수식어 윤문
    { pattern: /정확히/g, replace: '그야말로' },
    { pattern: /벽과 같은/g, replace: '벽과 같다' },
    { pattern: /벽과 같다\./g, replace: '벽과 같다.' },
    { pattern: /벽처럼\./g, replace: '벽처럼 단단하다.' },
    { pattern: /벽의 양\./g, replace: '벽과 같다.' },
    { pattern: /벽의 양/g, replace: '벽과 같음' },
    { pattern: /마치 벽/g, replace: '마치 벽과 같음' },

    // 6. 인명 결합 오역 및 보살피기 표현 보정
    { pattern: /엔도 모리와/g, replace: '엔도 마모루 일행과' },
    { pattern: /엔도 모리/g, replace: '엔도 마모루' },
    { pattern: /엔도 마모루라/g, replace: '엔도 마모루 일행' },
    { pattern: /귀찮은 좋은/g, replace: '남을 잘 돌봐주는' },
    { pattern: /사람으로 귀찮은/g, replace: '남을 돌봐주는 것을 좋아하는' },
    { pattern: /귀찮음 좋은/g, replace: '남을 잘 보살펴주는' },
    { pattern: /귀찮음이 좋은/g, replace: '남을 잘 보살펴주는' },
    { pattern: /언니 타입/g, replace: '누님 타입' },
    { pattern: /누나 타입/g, replace: '누님 타입' },
    { pattern: /확실한 사람/g, replace: '야무진 성격' },
    { pattern: /똑 부러지는 사람/g, replace: '야무진 성격' },

    // 7. 고엔지 등 주요 인물 설명문 직역체 보정
    { pattern: /멋지지만 가슴 속에 숨겼다/g, replace: '시크하지만 가슴속 깊이 간직한' },
    { pattern: /가슴 속에 숨겼다/g, replace: '가슴속 깊이 간직한' },
    { pattern: /가슴 속에 숨긴/g, replace: '가슴속 깊이 간직한' },
    { pattern: /가슴속에 숨긴/g, replace: '가슴속 깊이 간직한' },
    { pattern: /축구에 대한 생각은/g, replace: '축구에 대한 열정은' },
    { pattern: /축구에 대한 생각/g, replace: '축구에 대한 열정' },
    { pattern: /축구에 대한 마음은/g, replace: '축구에 대한 열정은' },

    // 8. 매니저(관리자) 및 왠지 모르게 오역 보정
    { pattern: /왜 관리자를/g, replace: '어째서인지 매니저를' },
    { pattern: /왜 관리자/g, replace: '어째서인지 매니저' },
    { pattern: /관리자를/g, replace: '매니저를' },
    { pattern: /관리자/g, replace: '매니저' },
    { pattern: /부원 이외는/g, replace: '부원 이외에는' },
    { pattern: /部員/g, replace: '부원' },

    // 9. 소속 팀 한자 독음 및 훈독 오역 보정
    { pattern: /카미나리몬 첫 팀/g, replace: '라이몬 1군' },
    { pattern: /카미나리몬 퍼스트/g, replace: '라이몬 1군' },
    { pattern: /카미나리몬 세컨드/g, replace: '라이몬 2군' },
    { pattern: /카미나리몬 중학교/g, replace: '라이몬 중학교' },
    { pattern: /카미나리몬 중/g, replace: '라이몬 중학교' },
    { pattern: /카미나리몬의/g, replace: '라이몬의' },
    { pattern: /카미나리몬/g, replace: '라이몬' },
    { pattern: /뇌문/g, replace: '라이몬' },
    { pattern: /월산국광중학교/g, replace: '갓산쿠니미츠 중학교' },
    { pattern: /월산국광중/g, replace: '갓산쿠니미츠 중학교' },
    { pattern: /월산국광/g, replace: '갓산쿠니미츠' },
    { pattern: /혁명 선발팀/g, replace: '레볼루션 선발' },
    { pattern: /혁명 선발/g, replace: '레볼루션 선발' },
    { pattern: /백련중학교/g, replace: '하쿠렌 중학교' },
    { pattern: /백련중/g, replace: '하쿠렌 중학교' },
    { pattern: /백련/g, replace: '하쿠렌' },
    { pattern: /만유사중학교/g, replace: '만유지 중학교' },
    { pattern: /만유사중/g, replace: '만유지 중학교' },
    { pattern: /만유사/g, replace: '만유지' },
    { pattern: /양화토중학교/g, replace: '요카토 중학교' },
    { pattern: /양화토중/g, replace: '요카토 중학교' },
    { pattern: /양화토/g, replace: '요카토' },
    { pattern: /목호천청수중학교/g, replace: '키도카와세이슈 중학교' },
    { pattern: /목호천청수중/g, replace: '키도카와세이슈 중학교' },
    { pattern: /목호천청수/g, replace: '키도카와세이슈' },
    { pattern: /테이코쿠 학원/g, replace: '제국학원' },
    { pattern: /테이코쿠학원/g, replace: '제국학원' },
    { pattern: /테이코쿠/g, replace: '제국' },
    { pattern: /영세 학원/g, replace: '에이세이 학원' },
    { pattern: /영세학원/g, replace: '에이세이 학원' },
    { pattern: /번개 일레븐/g, replace: '이나즈마 일레븐' },
    { pattern: /번개 재팬/g, replace: '이나즈마 재팬' },
    { pattern: /번개 레전드 재팬/g, replace: '이나즈마 레전드 재팬' },

    // 10. 핵심 고유 인명 및 성향 오역 정밀 보정
    { pattern: /천마를/g, replace: '텐마를' },
    { pattern: /천마의/g, replace: '텐마의' },
    { pattern: /천마와/g, replace: '텐마와' },
    { pattern: /천마/g, replace: '텐마' },
    { pattern: /신동을/g, replace: '신도를' },
    { pattern: /신동의/g, replace: '신도의' },
    { pattern: /신동과/g, replace: '신도와' },
    { pattern: /신동/g, replace: '신도' },
    { pattern: /안개 야/g, replace: '키리노' },
    { pattern: /안개야/g, replace: '키리노' },
    { pattern: /안개野/g, replace: '키리노' },
    { pattern: /안개 들/g, replace: '키리노' },
    { pattern: /구부러진 것이 싫다/g, replace: '올바르지 못한 것을 싫어한다' },
    { pattern: /구부러진 것을 싫어한다/g, replace: '올바르지 못한 것을 싫어한다' },
    { pattern: /굽은 것을 싫어한다/g, replace: '올바르지 못한 것을 싫어한다' },
    { pattern: /굽은 것이 싫다/g, replace: '불의를 싫어한다' },
    { pattern: /번장에서/g, replace: '골목대장으로,' },
    { pattern: /번장\./g, replace: '골목대장.' },
    { pattern: /번장/g, replace: '골목대장' },

    // 11. 팀명 직역 오역 및 리틀 기간트 관련 보정
    { pattern: /작은 기간트의/g, replace: '리틀 기간트의' },
    { pattern: /작은 기간트/g, replace: '리틀 기간트' },
    { pattern: /작은 자이언트/g, replace: '리틀 기간트' },
    { pattern: /작은 거인/g, replace: '리틀 기간트' },

    // 12. 기타 누락된 핵심 고유 인명 및 성향/기술 직역 교정 (겨울꽃, 삼국, 유채꽃 등 및 골을 숨긴다 교정)
    { pattern: /겨울꽃/g, replace: '후유카' },
    { pattern: /겨울 꽃/g, replace: '후유카' },
    { pattern: /겨울의 꽃/g, replace: '후유카' },
    { pattern: /삼국을/g, replace: '미쿠니를' },
    { pattern: /삼국의/g, replace: '미쿠니의' },
    { pattern: /삼국과/g, replace: '미쿠니와' },
    { pattern: /삼국/g, replace: '미쿠니' },
    { pattern: /유채꽃/g, replace: '나노바나' },
    { pattern: /산나물 아카네/g, replace: '야마나 아카네' },
    { pattern: /산나물/g, replace: '야마나' },
    { pattern: /물새/g, replace: '미도리' },
    { pattern: /하늘 들/g, replace: '소라노' },
    { pattern: /자랑으로 하는/g, replace: '특기로 하는' },
    { pattern: /자랑으로 삼는/g, replace: '특기로 하는' },
    { pattern: /자랑의/g, replace: '특기인' },
    { pattern: /골을 숨긴다/g, replace: '골문을 지킨다' },
    { pattern: /골을 숨긴/g, replace: '골문을 지킨' },
    { pattern: /골을 지킨다/g, replace: '골문을 지킨다' },
    { pattern: /숨긴다/g, replace: '지킨다' },
    { pattern: /숨긴/g, replace: '지킨' },
    { pattern: /수비의 요/g, replace: '수비의 핵' },
    { pattern: /수비의 요점/g, replace: '수비의 핵' },
    { pattern: /축구부의 수령/g, replace: '축구부의 감독' },
    { pattern: /부 활동/g, replace: '동아리 활동' },
    { pattern: /축구부 부장/g, replace: '축구부 주장' },
    { pattern: /축구부의 주장/g, replace: '축구부 주장' },
    { pattern: /부부장/g, replace: '부주장' },
    { pattern: /부장/g, replace: '주장' },
    { pattern: /캡틴으로 GK/g, replace: '주장이자 골키퍼' },
    { pattern: /캡틴으로/g, replace: '주장으로' },
    { pattern: /캡틴/g, replace: '주장' },
    { pattern: /탑 아래/g, replace: '공격형 미드필더' },
    { pattern: /톱 아래/g, replace: '공격형 미드필더' },

    // 13. 추가 인명 및 일어 잔재 오역 교정
    { pattern: /눈보라/g, replace: '후부키' },
    { pattern: /귀도/g, replace: '키도' },
    { pattern: /풍환/g, replace: '카제마루' },
    { pattern: /벽산/g, replace: '카베야마' },
    { pattern: /밤송이/g, replace: '쿠리마츠' },
    { pattern: /염강/g, replace: '소메오카' },
    { pattern: /반전/g, replace: '한다' },
    { pattern: /소림사/g, replace: '쇼린지' },
    { pattern: /육호/g, replace: '시시도' },
    { pattern: /그림자 들/g, replace: '카게노' },
    { pattern: /토문/g, replace: '도몬' },
    { pattern: /일지濑/g, replace: '이치노세' },
    { pattern: /일지세/g, replace: '이치노세' },
    { pattern: /기산/g, replace: '키야마' },
    { pattern: /녹천/g, replace: '미도리카와' },
    { pattern: /남택/g, replace: '미나미사와' },
    { pattern: /창간/g, replace: '쿠라마' },
    { pattern: /속수/g, replace: '하야미' },
    { pattern: /빈야/g, replace: '하마노' },
    { pattern: /천성/g, replace: '아마기' },
    { pattern: /차전/g, replace: '쿠루마다' },
    { pattern: /수렵야/g, replace: '카리야' },
    { pattern: /영산/g, replace: '카게야마' },
    { pattern: /비응/g, replace: '토비타카' },
    { pattern: /우도궁/g, replace: '우츠노미야' },
    { pattern: /입향거/g, replace: '타치무카이' },
    { pattern: /강해/g, replace: '츠나미' },
    { pattern: /목구레/g, replace: '코구레' },
    { pattern: /부동/g, replace: '후도' },
    { pattern: /좌구간/g, replace: '사쿠마' },
    { pattern: /원전/g, replace: '겐다' },
    { pattern: /변견/g, replace: '헨미' },
    { pattern: /소산/g, replace: '사키야마' },
    { pattern: /동면/g, replace: '도멘' },
    { pattern: /들꽃/g, replace: '노자키' },
    { pattern: /삼촌/g, replace: '모리무라' },
    { pattern: /구판/g, replace: '쿠사카' },
    { pattern: /개범/g, replace: '미나호' },
    { pattern: /진명부/g, replace: '마나베' },
    { pattern: /철각/g, replace: '테츠카도' },
    { pattern: /순목/g, replace: '마타기' },
    { pattern: /시천/g, replace: '이치카와' },
    { pattern: /서원/g, replace: '니시조노' },
    { pattern: /송풍/g, replace: '마츠카제' },
    { pattern: /검성/g, replace: '츠루기' },
    { pattern: /우궁/g, replace: '아메미야' },
    { pattern: /야판/g, replace: '노사카' },
    { pattern: /일성/g, replace: '이치호시' },
    { pattern: /길량/g, replace: '키라' },
    { pattern: /회기/g, replace: '하이자키' },
    { pattern: /도삼/g, replace: '이나모리' },
    { pattern: /소승환/g, replace: '코조마루' },
    { pattern: /빙포/g, replace: '히우라' },
    { pattern: /만작/g, replace: '만사쿠' },
    { pattern: /암호/g, replace: '이와토' },
    { pattern: /오입/g, replace: '오쿠이리' },
    { pattern: /도성/g, replace: '미치나리' },
    { pattern: /강진/g, replace: '고진' },
    { pattern: /일화/g, replace: '히요리' },
    { pattern: /해복/g, replace: '우미하라' },
    { pattern: /음무/g, replace: '오토나시' },
    { pattern: /목야/g, replace: '키노' },
    { pattern: /뇌문 여름미/g, replace: '라이몬 나츠미' },
    { pattern: /대등/g, replace: '사사토' },
    { pattern: /벚꽃 피는 벚꽃/g, replace: '사쿠라자키 사쿠라' },
    { pattern: /목소로/g, replace: '키소지' },
    { pattern: /백룡/g, replace: '하쿠류' },

    // 14. 문맥 및 명사 형태 어색함 보정
    { pattern: /축구 야로/g, replace: '축구 바보' },
    { pattern: /축구 녀석/g, replace: '축구 바보' },
    { pattern: /축구 애호가/g, replace: '축구 바보' },
    { pattern: /축구하자/g, replace: '축구하자!' },
    { pattern: /하자는/g, replace: '하자고' },
    { pattern: /뜨거운 마음을/g, replace: '뜨거운 열정을' },
    { pattern: /뜨거운 마음/g, replace: '뜨거운 열정' },
    { pattern: /뜨거운 생각/g, replace: '뜨거운 열정' },
    { pattern: /난공불락의 요새를 쌓는다/g, replace: '난공불락의 요새를 구축했다' },
    { pattern: /난공불락의 요새를 쌓았다/g, replace: '난공불락의 요새를 구축했다' },
    { pattern: /채용으로 팀을/g, replace: '지휘로 팀을' },
    { pattern: /아름다운 채용에/g, replace: '아름다운 지휘에' },
    { pattern: /보살핌이 좋은/g, replace: '남을 잘 돌봐주는' },
    { pattern: /보살핌이 잘/g, replace: '남을 잘 돌봐주는' },
    { pattern: /숨겨진 팬이/g, replace: '숨은 팬이' },
    { pattern: /숨겨진 팬/g, replace: '숨은 팬' },
    { pattern: /마음속 깊이 따르고 있다/g, replace: '마음속 깊이 따르고 있다' },
    { pattern: /진심으로 따르고 있다/g, replace: '마음속 깊이 따르고 있다' },

    // 15. 준족(빠른 발) 및 필드 질주 묘사 정밀 교정 (사용자 피드백 보완)
    { pattern: /뒤뒤지지/g, replace: '뒤지지' },
    { pattern: /뒤뒤지/g, replace: '뒤지' },
    { pattern: /슌족을/g, replace: '빠른 발을' },
    { pattern: /슌족의/g, replace: '빠른 발의' },
    { pattern: /슌족/g, replace: '빠른 발' },
    { pattern: /순족을/g, replace: '빠른 발을' },
    { pattern: /순족의/g, replace: '빠른 발의' },
    { pattern: /순족/g, replace: '빠른 발' },
    { pattern: /준족을/g, replace: '빠른 발을' },
    { pattern: /준족의/g, replace: '빠른 발의' },
    { pattern: /준족/g, replace: '빠른 발' },
    { pattern: /질풍과 같이/g, replace: '질풍처럼' },
    { pattern: /질풍의 여파로/g, replace: '질풍처럼' },
    { pattern: /필드를 달려간다/g, replace: '그라운드를 누빈다' },
    { pattern: /필드를 달려가/g, replace: '그라운드를 누벼' }
  ];

  // 규칙들을 문자열에 전역 치환 적용합니다.
  rules.forEach(rule => {
    refined = refined.replace(rule.pattern, rule.replace);
  });

  return refined;
}
